artifacts-root: artifacts # this is the root directory where all the artifacts will be stored

data_ingestion : 
  root_dir : artifacts/data_ingestion
  source_URL : "data/telecom_churn.csv"
  local_data_file : artifacts/data_ingestion/data.csv

data_validation :
  root_dir : artifacts/data_validation
  local_data_file : artifacts/data_ingestion/data.csv
  STATUS_FILE : artifacts/data_validation/status.txt

data_transformation :
  root_dir : artifacts/data_transformation
  data_path : artifacts/data_ingestion/data.csv
  preprocessor_path : artifacts/data_transformation/preprocessor.pkl

model_trainer :
  root_dir : artifacts/model_trainer
  train_data_path : artifacts/data_transformation/train.csv
  test_data_path : artifacts/data_transformation/test.csv
  model_name : model.joblib

model_evaluation :
  root_dir : artifacts/model_evaluation
  test_data_path : artifacts/data_transformation/test.csv
  model_path : artifacts/model_trainer/model.joblib
  metrics_file_path : artifacts/model_evaluation/metrics.json






